### PR TITLE
Explain mutual recursion.

### PR DESCRIPTION
**Pull request by tasshin**
This covers part of #14 - namely declarepath and providepath, using the example from the other part of the wiki. I don't think this is there yet - it doesn't cover local-declarepath (which I partially get - it's like an anonymous path, and declarepath just names that?), how and why you would use these vs. recursive-path, and how recursive-path is implemented (if that's necessary).

### CODE REVIEW

**Comment by tasshin** [comment]
We also probably need an example of mutually recursive paths.

**Comment by nathanmarz** [comment]
It's helpful to look at the implementation of these things: https://github.com/nathanmarz/specter/blob/master/src/clj/com/rpl/specter.cljc#L101

`local-declarepath` lets you declare a path anonymously which can be provided later. But it can be used in the meantime in other path definitions. This is how recursion and mutual recursion is enabled.

**Comment by tasshin** [comment]
Yes, I had found the source but was chewing on how to explain the concepts (both to myself and others ;) ). Thanks for the pointers, I re-used adaptations of your explanations in the doc. (As I am wont to do.)

Here is a better draft, which should get the job done, except I don't much like the example of mutually recursive paths, for reasons that will be obvious when you read it. Do you have an example you can adduce for this purpose?

**Comment by tasshin** [comment]
After discussion in Slack, this should be good to go, but happy to make further edits if needed.

**Pull request merged**
